services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    container_name: balance-rust-app
    working_dir: /usr/src/myapp
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/myapp
    command: sleep infinity

  redis:
    image: redis:8.2.2-alpine3.22

  mysql:
    image: mysql:8.0
    ports:
      - "3620:3306"
    volumes:
      - ./docker/mysql/general-logs:/var/log/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: yes
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
