services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    container_name: balance-rust-app
    working_dir: /usr/src/myapp
    volumes:
      - .:/usr/src/myapp
    command: sleep infinity

  redis:
    image: redis:8.2.2-alpine3.22

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
